### ISSUE TITLE
When adding a local section there is a problem with the weight that is empty

### ISSUE THREAD

**Issue by akramsarkis** [Geeks-Solutions/nuxt-sections#102]
- [x] When adding a local section there is a problem with the weight that is empty and consequently I cannot save the page where it is added

### Acceptance testing

- [ ] When I add a local section, i must be able to save the page

**Comment by mahfouzhseineweev** [comment]
Automated test needed here:

* Write test to make sure all sections has weight when sent in the payload

**Comment by mahfouzhseineweev** [comment]
@akramsarkis I have added for you a local section on meta sections, once you confirm all good for this issue, please let me know so I can remove it as it should not remain on meta sections project

**Comment by akramsarkis** [comment]
> @akramsarkis I have added for you a local section on meta sections, once you confirm all good for this issue, please let me know so I can remove it as it should not remain on meta sections project

@mahfouzhseineweev I have one question, when I am adding it in my home page https://projectcnamenov.k8s-dev.geeks.solutions/, it is added after the other sections available and I can save the page without problem.

Now when I move to page 1 https://projectcnamenov.k8s-dev.geeks.solutions/page1, it is added in the top I mean before the other sections, why this ?

**Comment by mahfouzhseineweev** [comment]
@akramsarkis What you are mentioning is not relevant to this issue. However to answer you, you need to check the weight you have for your other sections as it seems you had old sections that were removed and for example the lowest section weight you had before adding the local section is bigger than the sections count in your page which will result to what you mentioned

**Comment by akramsarkis** [comment]
closing it
