### ISSUE TITLE
Have an icon showing in the language switcher when editing a section, to show in which language the site is opened

### ISSUE THREAD

**Issue by akramsarkis** [Geeks-Solutions/nuxt-sections#13]
- [x] Have an icon showing in the language switcher when editing a section, to show in which language the site is opened

**Acceptance testing**

- [x] Have an icon showing in the language switcher when editing a section, to show in which language the site is opened and then which translation is needed to see the content when submitting the data of the section

**Comment by akramsarkis** [comment]
@mahfouzhseineweev  please to tag julien and add your suggestion

**Comment by mahfouzhseineweev** [comment]
I would like to suggest, instead of adding icon or anything.
We just make the language selected by default regarding which language is the site on when open creating or editing a section, what do you think ? @jfayad

**Comment by jfayad** [comment]
I like your suggestion, but I still think the icon is needed. When you are editing multiple content it's easy to get lost about the language you are on etc.. especially if you start editing multiple languages at the same time

**Comment by akramsarkis** [comment]
Perfect all good
