### ISSUE TITLE
Feedback required updates to be done on the module

### ISSUE THREAD

**Issue by mahfouzhseineweev** [Geeks-Solutions/nuxt-sections#4]
- [ ] If sections settings are given as an object by the host project, return an error on the library and force them to be sent as array.

* When the admin save a page that has sections with settings in Object format, the nuxt module should respond with an error that shows in the toast to let the admin knows that all section settings should be in Array format.

- [ ] global upload function of the meta component should simply return the data in the correct format so as an array and including media_id and so it only needs to be added to the settings when returned

* When the admin select a media from the media meta component mini BO, the selection will return an array of the media having the media_id and the url. ex.: ``[{media_id: 1, ur: 'https://URL'}]`` will be returned to the sections and will be assigned to the media type inside the settings. This can be checked in the payload when editing or creating a section and saving the page **It is the PUT request to update section page**

**Comment by akramsarkis** [comment]
@mahfouzhseineweev I guess this is done, if this is the case, please to close it
