### ISSUE TITLE
Information icon, project id and unlock/lock sections

### ISSUE THREAD

**Issue by akramsarkis** [Geeks-Solutions/nuxt-sections#46]
- [ ] When there is an information icon for a section, in the section listing, have the info shown while clicking on it and not hovering
- [x] We noticed that for the blogs sections some does not have the "by " mention available which is wrong
- [x] Add in the settings the project id 

**Acceptance testing**

- [ ] When there is an information icon for a section, in the section listing, have the info shown while clicking on it and not hovering
- [x] We noticed that for the blogs sections some does not have the "by " mention available which is wrong , it must be fixed
- [x] Add in the settings the project id

**Comment by mahfouzhseineweev** [comment]
Estimated 20mn

**Comment by mahfouzhseineweev** [comment]
> When there is an information icon for a section, in the section listing, have the info shown while clicking on it and not hovering

For the tooltip as discussed, I checked if there is a way to have the native html tooltip works on mobile touch but there isn't. The only way is to create custom tooltip that responds to touch or click events

**Comment by akramsarkis** [comment]
@mahfouzhseineweev 

- [ ] There is a small adjustment to be done on the display of the settings popup that is truncated

<img width="889" alt="Screenshot 2024-11-19 at 11 48 34" src="https://github.com/user-attachments/assets/26bcdbb3-3cea-4e4b-9716-1c7b6f14bed5">

**Comment by akramsarkis** [comment]
The missing point will be done in issue https://github.com/Geeks-Solutions/nuxt-sections/issues/92
