### ISSUE TITLE
Render request from one section to another

### ISSUE THREAD

**Issue by akramsarkis** [Geeks-Solutions/nuxt-sections#50]
- [x] Render request from one section to another
- [x] When you access a page with query strings they are showing in the name of the page when editing it, please to adjust this to have only the page name showing

<img width="1161" alt="Screenshot 2024-09-03 at 14 18 39" src="https://github.com/user-attachments/assets/7fefc3cd-2e4a-496a-944b-2f85748ce506">

@mahfouzhseineweev as discussed as I don't have the details you need to update the issue with the details and update needed in the library and as well with the acceptance testing I need to do

### **Acceptance testing**

- [ ] When you access a page with query strings they are showing in the name of the page when editing it, please to adjust this to have only the page name showing
- [ ]

**Comment by akramsarkis** [comment]
Hussein Mahfouz
[17 hours ago](https://mattermost.gl.eweev.com/eweev/pl/g9jhmo5gjfy8znocaqc6c9rbsr)
Hello @Julien Fayad Regarding your request about refreshing all section views that are using the qs that has changed. 
This needs to use the section-types API which requires sections admin token, so this is not an option currently.

Note that the way the refresh section is currently done allows refreshing multiple sections by they should be called specifically by their names 

4 replies

Akram Sarkis
[15 hours ago](https://mattermost.gl.eweev.com/eweev/pl/t1ot81o7abnz8ddffx7zfxjfyo)
@Julien Fayad  just as reminder in case you did not see it


Julien Fayad
[14 hours ago](https://mattermost.gl.eweev.com/eweev/pl/8rpy5ck65jbx7ph8mipo6jsebw)




you mean to know what qs a section relies on requires access to the section-types endpoint?

We could eventually expose the qs requirement in the section content when rendering a page to avoid this extra call to the section-types endpoint.. would that solve the issue ?

As for your last point, I didn't get it... I mean yes you need to specifically refresh a section by using its name, but the library will be handling this, that's what we discussed, isn't it ?


Hussein Mahfouz
[14 hours ago](https://mattermost.gl.eweev.com/eweev/pl/shkwgyh6nbf85ppeqbsoua8tuh)
Forget about the last point if we can expose the qs requirements somewhere then that will work


Hussein Mahfouz
[13 hours ago](https://mattermost.gl.eweev.com/eweev/pl/r8147qqqdtrrfdsq9d1hsbd3ir)
The library will handle all, the only thing the host project will do is that a section will emit an event with the qs updated value

So from what Hussein said, you need to expose the query string requirement somewhere before he can work on this issue

**Comment by mahfouzhseineweev** [comment]
@akramsarkis To test this on maiori site, you need to:

* Make sure the pagination still works properly on the products list
* In the products lists use the Types to switch between standing lamps and table lamps, check the network to make sure the dynamic sections that has type_id are refreshed **API call sent**, on the front make sure the view data are updated correctly

**Comment by akramsarkis** [comment]
> @akramsarkis To test this on maiori site, you need to:
> 
> * Make sure the pagination still works properly on the products list
> * In the products lists use the Types to switch between standing lamps and table lamps, check the network to make sure the dynamic sections that has type_id are refreshed **API call sent**, on the front make sure the view data are updated correctly

@mahfouzhseineweev 

- For the listing it is fine
- Now for the types when I click on table lamps, there is no lamps showing at all, I checked in the network and the api return no product for a reason, however if I a in desktop and from the menu I select table lamps I have the lamp showing as expected.
- More of this you are speaking of type_id but on the 2 api call sent I am not finding any type_id , so not sure if all good there

**Comment by akramsarkis** [comment]
all good, closing
