### ISSUE TITLE
QA Global Sections management

### ISSUE THREAD

**Issue by akramsarkis** [Geeks-Solutions/nuxt-sections#51]
<details>
<summary>Global instance in general</summary>

- [ ] Let's modify the name of Global section to Global instance
</details>

<summary> Create global instance</summary>

- [x] The create global instance let's add  a button after the Add an ew section " Add a global instance", " Ajouter une instance globale"

<img width="776" alt="Screenshot 2024-09-11 at 14 11 57" src="https://github.com/user-attachments/assets/22ec7c54-1c6d-4d49-a57c-cf1c4aaf8939">

- [x] When you click on the button, you have the list of sections types showing with in the top this sentence
"Select a section type to create a global instance of it", "Sélectionner un type de section pour créer une instance globale de celle-ci"
- [x] When you click on one section type you have a form showing with:
- an input field to enter the global instance name
- then an option to add it automatically to new page or not 
- the form corresponding to the section list selected empty
- [x] You fill the form then submit data and the global instance is added to the listing of global instance that is like you did it actually, the difference is that only the global instance will show there
- [x] When you click on one global instance, it is added to the page
- [x] I tried to create a global instance, I filled in the fields then presses submit data and I got an error that the global section can't be updated and indeed you are calling the Put endpoint instead of the Post endpoint

</details>

<details>
<summary> Edit global section</summary>

- [x] Edit option for the global section is the same as the one for normal section, as mentioned in the issue we need it different ,  for example in red like proposed in the description
- [x] When editing a global instance, the global instance name input should not show as we can't change the name
</details>

### **Acceptance testing**

<details>
<summary>Global instance in general</summary>

- [x] Let's modify the name of Global section to Global instance
</details>

<details>
<summary>Global instance listing</summary>

- [x] There is no indication to the user on how he can create a global section, it is better to have one, like a sentence above the listing saying " To create a global section click on one section that is disabled.
</details>

<details>
<summary> Create global instance</summary>

- [x] When you click on the button, the form to add a global instance shows with first  
- an input field to enter the global instance name
- then an option to add it automatically to new page or not 
- The section types listing to select the one I want 
- the form corresponding to the section list selected empty
- [x] You fill the form then submit data and the global instance is added to the listing of global instance that is lik you did it actually, the difference is that only the global instance will show there
- [x] When you click on one global instance, it is added to the page
- [x] I tried to create a global instance, I filled in the fields then presses submit data and I got an error that the global section can't be updated and indeed you are calling the Put endpoint instead of the Post endpoint

</details>

<details>
<summary> Edit global section</summary>

- [x] Edit option for the global section is the same as the one for normal section, as mentioned in the issue we need it different ,  for example in red like proposed in the description
- [x] When editing a global instance, the global instance name input should not show as we can't change the name
</details>

**Comment by mahfouzhseineweev** [comment]
### Report:

The issue took more time than expected because of the update for the configurable and dynamic sections which requires a specific management for each one aside.

And this is because of the render and options API calls that are required to render the section. This management was not accounted for when estimated the issue as I had in mind at first only adding global instance for static section types.

The updates can be seen in details inside the PR
