### ISSUE TITLE
QA Global instance round 2

### ISSUE THREAD

**Issue by akramsarkis** [Geeks-Solutions/nuxt-sections#52]
<details>
<summary> Categories articles form</summary>

- [x] The form is truncated when creating a global section for it ( same all the sections when they are big)

<img width="1011" alt="Screenshot 2024-09-12 at 16 52 18" src="https://github.com/user-attachments/assets/fff28c36-f122-4f39-ac81-21552166d502">
</details>

<details>
<summary> Edit global sections </summary>

- [x] When editing successfully a global section there is a typo in the message it should be " Global section updated successfully"

</details>

<details>
<summary> Add automatically section to  newly created page </summary>

- [x] In the pro page I have the global section MaioriHtmlSection that is ticked to be added automatically but when i created a new page pagetestnew it is not there when editing the page
- [x] For the configurable section for example Global instance selective article it is added but not the same way as on pro

**Pro page**

<img width="1656" alt="Screenshot 2024-09-12 at 17 49 44" src="https://github.com/user-attachments/assets/223df42d-aa4e-4073-87d5-17e9eca74aac">

**pagetestnew**

<img width="1670" alt="Screenshot 2024-09-12 at 17 51 37" src="https://github.com/user-attachments/assets/c9524789-78b2-4d24-90e2-2864639a37e0">

</details>

### **Acceptance testing**

<details>
<summary> Categories articles form</summary>

- [x] The form is truncated when creating a global section for it ( same all the sections when they are big)
</details>

<details>
<summary> Edit global sections </summary>

- [x] When editing successfully a global section there is a typo in the message it should be " Global section updated successfully"

</details>

<details>

<details>
<summary> Add automatically section to  newly created page </summary>

- [x] In the pro page I have the global section MaioriHtmlSection that is ticked to be added automatically but when i created a new page pagetestnew it is not there when editing the page and it should be
- [x] For the configurable section for example Global instance selective article it is added but not the same way as on pro, it should be the same

</details>

**Comment by mahfouzhseineweev** [comment]
> For the configurable section for example Global instance selective article it is added but not the same way as on pro

Here is the link of the thread discussion about this point on mattermost https://mattermost.gl.eweev.com/eweev/pl/7zw7o876s3ggijmoak4kq9ihxa

**Comment by akramsarkis** [comment]
@mahfouzhseineweev there is still problem with the forms like you can see below


<img width="1636" alt="Screenshot 2024-09-13 at 16 14 53" src="https://github.com/user-attachments/assets/e8d603c0-ce8f-4056-9e25-f4ffb55dd231">
<img width="1631" alt="Screenshot 2024-09-13 at 16 30 28" src="https://github.com/user-attachments/assets/fed47c8f-3aa5-4b9d-96b8-2cfb2a87f7bc">
<img width="1668" alt="Screenshot 2024-09-13 at 16 31 39" src="https://github.com/user-attachments/assets/1330f361-8f50-498a-b5eb-82e16fbf5a9e">

**Comment by akramsarkis** [comment]
all good, closing it
