### ISSUE TITLE
Put all the non installed static sections, and locked dynamic/configurable ones in a separate tab 

### ISSUE THREAD

**Issue by akramsarkis** [Geeks-Solutions/nuxt-sections#67]
- [x] When you click on the Add new section in the popup we need to have 3 tabs
- Add new sections that should be renamed Available sections ( Sections disponibles )
- Add a Global instance ( Ajouter une instance globale )
- Inventory ( Inventaire)
- [x] Put all the non installed static sections, and locked dynamic/configurable ones in a separate tab  that is called Inventory and that will be after the add global section one,
- [x] When I create a section or activate one it should be removed from the inventory tab and added to the  Available section tab,  in case of lock /unlock, all the sections of the same app must be moved
- [ ] When from the availabe section tab I delete one section, it should be removed from the available section tab and added back to the inventory one

### **Acceptance testing**

- [x] When you click on the Add new section in the popup we need to have 3 tabs
- Add new sections that should be renamed Available sections ( Sections disponibles )
- Add a Global instance ( Ajouter une instance globale )
- Inventory ( Inventaire)
- [x] Put non installed static sections and locked dynamic/configurable one in a separate tab
- [x] When I create a section or activate one it should be removed from the inventory tab and added to the  Available section tab,  in case of lock /unlock, all the sections of the same app must be moved
- [ ] When from the availabe section tab I delete one section, it should be removed from the available section tab and added back to the inventory one

**Comment by akramsarkis** [comment]
@jfayad ,

The functionality is working fine except the remove static section as when deleting a section it is returning a 500 ( 15h17 lebanon time ), I am testing on Postman section dev

Here the sentry link error:

https://geeks-solutions.sentry.io/issues/6041457624/?project=5224485&query=is%3Aunresolved%20issue.priority%3A%5Bhigh%2C%20medium%5D&referrer=issue-stream&stream_index=0

Here the credentials if needed:

- Login : [a.sarkis+sectionswebsitedev@eweev.com](mailto:a.sarkis+sectionswebsitedev@eweev.com)
- Password: Goldman31
- 
Here the payload I am sending:

````
DELETE /api/v1/project/64d10222ab2be30008ce9342/section-types/sectiontest56 HTTP/1.1
Host: sections.k8s-dev.geeks.solutions
origin: https://sections.k8s-dev.geeks.solutions
token: SFMyNTY.g2gDdAAAAARtAAAADGxvZ2luX2ZpZWxkc3QAAAABbQAAAAVlbWFpbG0AAAAlYS5zYXJraXMrc2VjdGlvbnN3ZWJzaXRlZGV2QGV3ZWV2LmNvbW0AAAARcHJvamVjdF9sb2dnZWRfaW5tAAAAGDY0ODg3NDM4NTgyMTAwMDAwNzA0ZWM1MW0AAAAKdG9rZW5fdHlwZW0AAAAGbm9ybWFsbQAAAAd1c2VyX2lkbQAAABg2NGQxMDIyMzEzNTMxNjAwMDc4ZDM1NWJuBgBEwxrSkgFiAAFRgA.4e6IiI9lqQhCTya1eETzVyoOMxqpncKp00QI_qIr5lY

````

**Comment by akramsarkis** [comment]
@mahfouzhseineweev  we noticed on bug that Julien asked me to add here : When i try to add a section typ and I reach my limit so there is an error , the toggle is remaining enable which is wrong

**Comment by akramsarkis** [comment]
@mahfouzhseineweev I noticed right now that when I tried to unlock sections from the inventory,  when I press confirm it remains grayed out or nothing is happening for a reason I am not seeing error in the network . I need to refresh the page to have it work.

1. Go to blogs1 page http://sectionswebsite-saas.k8s-dev.geeks.solutions/blogs1 you will see sections not showing in edit mode
2. Click on add new section then go to inventory and try to unlock sections

**Comment by mahfouzhseineweev** [comment]
You said grayed out ? The sections to unlock are not showing grayed out @akramsarkis

**Comment by mahfouzhseineweev** [comment]
I have just tried to unlock the blogs sections, I put the private key and project ID and it worked

**Comment by akramsarkis** [comment]
No i mean the whole page showed as grayed out, not the section itself and the second time , nothing was grayed out but nothing was happening, I needed to refresh the page

**Comment by akramsarkis** [comment]
I'll try to do a video

**Comment by akramsarkis** [comment]
Hum now it is working,  I am no more able to reproduce,  I will try a bit again but it might be a connexion issue

**Comment by akramsarkis** [comment]
Ignore it @mahfouzhseineweev , I think it is connexion problem

**Comment by akramsarkis** [comment]
Now the toggl remains off
