### ISSUE TITLE
System to filter sections types in the listing

### ISSUE THREAD

**Issue by akramsarkis** [Geeks-Solutions/nuxt-sections#68]
- [ ] Modify the " Add global instance" button near the save one by " Create Global instance"
- [ ] When clicking on the Add a new section we have 3 tabs, available, global and inventory, the filter must be there for the 3 of them
- [ ] In case the global instance is empty we need a button "Create a global instance" and when clicking on it, it open  the same popup as when clicking on the button from the menu near save (previews should be enabled there)
- [ ] when we click on one tab, we need a system to filter sections types in the listing, Filter will run directly in the front end
- It should be on the top before the sections listing and in one line where you will have a  text field to filter by name, then a drop down to select the app you want to filter the sections by,  button to apply the filter and we need option to clear the filter too
- By name
- By app name ( drop down wit the existing one )

### **Acceptance testing**

- [x] Modify the " Add global instance" button near the save one by " Create Global instance"
- [x] When clicking on the Add a new section you need to have 2 tabs
- 1st one : Available sections
- 2nd one: Add global instance
- [x] In case the global instance is empty we need a button "Create a global instance" and when clicking on it, it open  the same popup as when clicking on the button from the menu near save (with sections previews enabled)
- [x] when we click on one tab, we need a system to filter sections types in the listing, Filter will run directly in the front end
- It should be on the top before the sections listing and in one line where you will have a  text field to filter by name, then a drop down to select the app you want to filter the sections by,  button to apply the filter and we need option to clear the filter too
- [x] Filtering sections types by name will show only one that correspond the the name entered
- [x] Filtering sections types by app name will show only the sections that app name is the one selected
- [x] This should be available and working as well for the global sections available

**Comment by jfayad** [comment]
search will run directly in the front end

**Comment by akramsarkis** [comment]
> @akramsarkis Revise point 2 please

Done @mahfouzhseineweev

**Comment by akramsarkis** [comment]
Don't forger the automated test @mahfouzhseineweev

**Comment by akramsarkis** [comment]
- [ ] It will more clear if before each filter you add "Filter by"
- [ ] For the clear button, have a hand to show we can click on it
- [ ] In French for the app drop down, you need to change the place holder to " Séléctionner un nom d'application"
- [ ] In the inventory why for the sections, the app is not showing like in the available section ? Consequently we cannot filter by app in the inventory

<img width="373" alt="Screenshot 2024-12-17 at 12 15 56" src="https://github.com/user-attachments/assets/53fdba75-a0e2-4eef-8a75-913b6d086f68" />
<img width="370" alt="Screenshot 2024-12-17 at 12 16 18" src="https://github.com/user-attachments/assets/5c1177b4-8b01-4298-87ea-6c82aef82a09" />

**Comment by mahfouzhseineweev** [comment]
> In the inventory why for the sections, the app is not showing like in the available section ? Consequently we cannot filter by app in the inventory

@akramsarkis The section is not created and not returned by the /types so it does not have an app name

**Comment by akramsarkis** [comment]
all good
