### ISSUE TITLE
Update of the Settings  popup for the page

### ISSUE THREAD

**Issue by akramsarkis** [Geeks-Solutions/nuxt-sections#70]
- [x]  Remove from the settings the below
- Languages
- Favicon
- Cookies consent including the GTM field showing when the cookie consent is ticked
- The CSS preset management
- [x] For the CSS keep only the possibility to upload a custom CSS and be able to remove it once it is uploaded
- [x] Make sure that the Settings popup is no more truncated

<img width="940" alt="Screenshot 2024-12-10 at 16 00 03" src="https://github.com/user-attachments/assets/65d26602-e02f-470c-82d2-f8b55b2748eb">

- [x] **IMPORTANT**: If a custom css is uploaded, you need **FIRST** to apply the project css selected in the BO project info, and then the CSS uploaded for the page
- The css for the project you will get it in the get page response under the metadata object where there is a project_metadata object

<img width="752" alt="Screenshot 2024-12-10 at 15 52 58" src="https://github.com/user-attachments/assets/df9498b2-0b5e-449b-af93-a29f72c696e8">
- [ ] Add automated tests to cover the changes

### Acceptance testing

- [x] When I open the page settings I must no more see :
- Languages
- Favicon
- Cookies consent including the GTM field showing when the cookie consent is ticked
- The CSS preset management
- [x] In the page settings there must be the possibility to upload a custom css for the page and as well to remove it
- [x] When a custom css for the page is uploaded and the settings are saved, the css of the project must apply first and then the one of the page
- [x] Automated tests must be created to cover the change

**Comment by akramsarkis** [comment]
@mahfouzhsein 

1) for this one no automated test ?
2) Please fo my testing to provide to me a css i can use for the project and one for my page telling me when applying the one of the page what difference I will see compare to when only the project one is applied

**Comment by mahfouzhseineweev** [comment]
@akramsarkis 

1. It is just about removing old fields and make sure css is applied correctly, which is why I haven't thought of any test to perform
2. For the project CSS, use the sections look one, for the custom CSS I will provide one in the issue that will change the look of the SimpleMenu section when it is used as a Header

**Comment by akramsarkis** [comment]
@mahfouzhseineweev 

I have one feedback:

- [ ] When from BO section you select only French language and you save then on the site you edit a section, there is only one language showing but the english one not the french one as even if french was selected, you are seeing the content you entered for english.

You can use still my account a.sarkis+cnameprojectnov@eweev.com/ Goldman31 and set for it the language to fr

**Comment by mahfouzhseineweev** [comment]
> When from BO section you select only French language and you save then on the site you edit a section, there is only one language showing but the english one not the french one as even if french was selected, you are seeing the content you entered for english.

I think you configured your sections project to have only FR which means you site does not have other localization than FR. Which also means that you should have tested using /fr/.

I assume what you did is that you opened your site in english locale correct ?

**Comment by mahfouzhseineweev** [comment]
@akramsarkis As discussed, both points are not valid since they should be part of a new issue on the vue-cli-plugin library and not related to the update I did. I also confirm that the preset are updated on the website after it is selected from the BO

**Comment by akramsarkis** [comment]
> @akramsarkis As discussed, both points are not valid since they should be part of a new issue on the vue-cli-plugin library and not related to the update I did. I also confirm that the preset are updated on the website after it is selected from the BO

@mahfouzhseineweev you said you confirm that the preset are updated on the website, how are seeing this ?  Because i am refreshing the page and I am not seeing any changes

**Comment by mahfouzhseineweev** [comment]
> you said you confirm that the preset are updated on the website, how are seeing this ?

Check the network for the preset you chose, it should be downloaded and then check the dom of your page, you should see the preset css added.

Now for the changes not showing it depends on the css selectors in the page, most of them were part of the blogs sections which can be clearly noticed.

For the others, they can be noticed by the font-family but it is not applied due to the problem that I should fix @akramsarkis

**Comment by akramsarkis** [comment]
The 2 points remaining will be fixed in separate issues below as those are not related to the work done for this issue:

- https://github.com/Geeks-Solutions/vue-cli-plugin-sections/issues/28
- https://github.com/Geeks-Solutions/vue-cli-plugin-sections/issues/27
