### ISSUE TITLE
Optimisation of the Edit mode of a page

### ISSUE THREAD

**Issue by akramsarkis** [Geeks-Solutions/nuxt-sections#71]
- [ ] We need when adding or editing a section have instead of the popup a side bar displayed on the left of the site
- The size of the site is reduced
- This will allow when you are doing changes to see the changes directly on the site
- [ ] Allow the user to resize the width of the side bar and then consequently the one of the site 

### **Acceptance testing**

- [ ] Instead of the popup to edit a section we should have a side bar on the left of the site
- [ ] The sidebar edition must work exactly as the popup, the only difference is that you see the changes directly on the site
- [ ] The user must be able to resize the width of the sidebar and consequently the one of the site

**Comment by akramsarkis** [comment]
Feedbacks demo:


- [ ] For the width of the edit part, let's have as minimum the one of the button like below

<img width="431" alt="Screenshot 2024-10-30 at 11 37 02" src="https://github.com/user-attachments/assets/36179b55-2d24-4e5d-935d-e1f942fc259a">

- [ ] Remove the submit data button as the changes reflect directly on the page and it is no more needed
- [ ] Near the name of the section that is edited, add the Anchor icon but smaller than the one showing for the section and when clicking in it it will scroll till the section in question
- [ ] You need to adapt the  media navigator or make it show above when opened as now it is very complicated to use it

<img width="1634" alt="Screenshot 2024-10-30 at 11 40 02" src="https://github.com/user-attachments/assets/09c25627-8127-4ab8-9049-2ff4fcc58e30">

**Comment by mahfouzhseineweev** [comment]
> Remove the submit data button as the changes reflect directly on the page and it is no more needed

This is not possible without multiple code rewrites as it is a breaking change update even though the section is updated but the submit is needed to reflect these updates in the options, some changes could be taken into consideration without submitting data but not all of them

**Comment by akramsarkis** [comment]
@jfayad all good now, I let you just check the comment above of hussein about the Submit button before closing the issue

**Comment by jfayad** [comment]
> > Remove the submit data button as the changes reflect directly on the page and it is no more needed
> 
> This is not possible without multiple code rewrites as it is a breaking change update even though the section is updated but the submit is needed to reflect these updates in the options, some changes could be taken into consideration without submitting data but not all of them

got you, is it possible then to show a popup to the editor who made changes but did not submit (and pressed the X to close the edit form instead) ? The popup will warn the user that his changes will be lost and if wants to proceed, we revert his changes in that particular section ?

if clicking the submit button is mandatory (and not pressing it could cause random errors), then not pressing it should put back the section's content to what it was

**Comment by mahfouzhseineweev** [comment]
@jfayad Catching changes inside a complex array of objects and different types is doable but not easy and may not work at some points. Can we instead warn the user each time He wants to close the edit mode section ?

**Comment by jfayad** [comment]
@mahfouzhseineweev you don't need to catch any changes... you just need to keep a copy of the settings and if the X is pressed, then you restore these...

**Comment by akramsarkis** [comment]
All good now, when I edit a section but I press X, the change is not reflected on the section, if I press Submit data , the change is taken into consideration
