### ISSUE TITLE
Custom css bug to fix

### ISSUE THREAD

**Issue by akramsarkis** [Geeks-Solutions/nuxt-sections#86]
- [x] When you select a custom CSS and you save, then you  select none or a preset css, the style of the custom css is still there which is wong

### **Acceptance testing**

- [x] When you select a custom CSS and you save, then you  select none or a preset css, the style must be modified in function of it

**Comment by mahfouzhseineweev** [comment]
Estimated: 0.5h

**Comment by akramsarkis** [comment]
all good now , closing it
