### ISSUE TITLE
When I edit a section I am scrolled up to the top of the page

### ISSUE THREAD

**Issue by akramsarkis** [Geeks-Solutions/nuxt-sections#94]
- [x] When I edit a section I am scrolled up to the top of the page which is wrong I need to be automatically. scrolled to the section I am editing

### Acceptance testing

- [x] When I edit a section I am scrolled up to the top of the page which is wrong I need to be automatically. scrolled to the section I am editing

**Comment by mahfouzhseineweev** [comment]
@jfayad What tests I should add for this one ?

**Comment by jfayad** [comment]
You can automate a test here to make sure that when you press the edit button, you still have the section you are editing in the viewport

**Comment by akramsarkis** [comment]
@mahfouzhsein please to review the issue and adjust the estimate

**Comment by akramsarkis** [comment]
All good, closing it
