### ISSUE TITLE
When we are in edit mode, let's have for each section a small button on the right and when clicking on it the edit options shows for the section

### ISSUE THREAD

**Issue by akramsarkis** [Geeks-Solutions/nuxt-sections#95]
- [x] When we are in edit mode, let's have for each section a small button on the right and when clicking on it the edit options shows for the section
- For the icon, we can use the gear icon we have already and put it in small. no Tooltip needed
- The drag drop, edit, etc options must be hidden by default and when you click on the gear icon, it shows the option we have and the gear remain there
- When you click again on the gear, it hides the option

- [x] Automated tests

The goal of this is to not have the options hiding part of the sections in edit mode

### Acceptance testing

- [x] Have a gear icon in small on the right of the section
- [x] Have the edit, drag and drop, etc options hidden by default
- [x] Clicking on the gear icon shows the 4 options we have
- [x] Clicking back on the gear icon will hide them again
- [x] Automated tests needs to be implemented

**Comment by mahfouzhseineweev** [comment]
This issue is missing more details about:

* The button to be added (icon or label)

* It will replace the existing button options below
<img width="224" alt="image" src="https://github.com/user-attachments/assets/7d36438b-07b1-4c4e-9a18-738a7ba0eb0b" />

* And then when clicking on it they will show, then what happen to it ?

* Also the goal behind this issue is not clear

**Comment by akramsarkis** [comment]
> @akramsarkis
> 
> This issue is missing more details about:
> 
> * The button to be added (icon or label)
> * It will replace the existing button options below
> 
> <img alt="image" width="224" src="https://private-user-images.githubusercontent.com/101403093/394819133-7d36438b-07b1-4c4e-9a18-738a7ba0eb0b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM5MzQyMjcsIm5iZiI6MTczMzkzMzkyNywicGF0aCI6Ii8xMDE0MDMwOTMvMzk0ODE5MTMzLTdkMzY0MzhiLTA3YjEtNGM0ZS05YTE4LTczOGE3YmEwZWIwYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIxMVQxNjE4NDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03OGJiOTI0MmM4MDQ5ZDU3NzNjMTY0MDQ1NTU4Mjk0NzdmM2Q4YjJiNThiZGVkMDVhMzQ5NmUxNzU5ZDEwM2JlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.EMlKT6Y-fMg5qxQNvszaqkqJrDj-6Xh1fMVQPki8yfA">
> * And then when clicking on it they will show, then what happen to it ?
> * Also the goal behind this issue is not clear


1) It is an icon but julien needs to tell us what icon is needed and what tooltip it should have
2) Well it will hide them and when you click on the option, the it shows the option we have
3) Well when you click on the options to show the 4 options for the section, should remain there and when you click back on it it hide the 4 options
4) The goal of this is to not have the options hiding part of the sections in edit mod


@jfayad 

1) What icon you want us to use for this option and what tooltip it should have

**Comment by mahfouzhseineweev** [comment]
Automated test needed for this one:

* Write test to make sure the options visibility is switched hidden/showing when clicking on the new icon option that we will add

**Comment by jfayad** [comment]
> > @akramsarkis
> > This issue is missing more details about:
> > 
> > * The button to be added (icon or label)
> > * It will replace the existing button options below
> > 
> > <img alt="image" width="224" src="https://private-user-images.githubusercontent.com/101403093/394819133-7d36438b-07b1-4c4e-9a18-738a7ba0eb0b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM5MzQyMjcsIm5iZiI6MTczMzkzMzkyNywicGF0aCI6Ii8xMDE0MDMwOTMvMzk0ODE5MTMzLTdkMzY0MzhiLTA3YjEtNGM0ZS05YTE4LTczOGE3YmEwZWIwYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIxMVQxNjE4NDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03OGJiOTI0MmM4MDQ5ZDU3NzNjMTY0MDQ1NTU4Mjk0NzdmM2Q4YjJiNThiZGVkMDVhMzQ5NmUxNzU5ZDEwM2JlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.EMlKT6Y-fMg5qxQNvszaqkqJrDj-6Xh1fMVQPki8yfA">
> > * And then when clicking on it they will show, then what happen to it ?
> > * Also the goal behind this issue is not clear
> 
> @mahfouzhseineweev
> 
> 1. It is an icon but julien needs to tell us what icon is needed and what tooltip it should have
> 2. Well it will hide them and when you click on the option, the it shows the option we have
> 3. Well when you click on the options to show the 4 options for the section, should remain there and when you click back on it it hide the 4 options
> 4. The goal of this is to not have the options hiding part of the sections in edit mod
> 
> @jfayad
> 
> 1. What icon you want us to use for this option and what tooltip it should have

for the icon, we can use the gear icon we have already and put it in small. no Tooltip needed

**Comment by akramsarkis** [comment]
@mahfouzhsein I updated the issue, so please to review it and adjust your estimate including the automated tests and QA

**Comment by akramsarkis** [comment]
All good, closing it
